import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import { inter } from "./fonts";
import Footer from "@/components/ui/Footer";
import BreadCrumbs from "@/components/ui/BreadCrumbs";




export const metadata: Metadata = {
  title: "AssetTrak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar/>
        <BreadCrumbs/>
        <main className="mx-3 md:mx-5 xl:mx-10 mt-5 min-h-screen">
    
          {children}
        </main>
        <Footer/>

      </body>
    </html>
  );
}
