import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import { inter } from "./fonts";




export const metadata: Metadata = {
  title: "AssetTrak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${inter.className} antialiased`}
      >
        <Navbar/>
        <main className="mx-10 mt-5">
          {children}
        </main>

      </body>
    </html>
  );
}
